export const INITIAL_BLOGS = [
  {
    id: 1,
    slug: "how-to-choose-the-best-email-marketing-agency-in-delhi",
    title: "How to Choose the Best Email Marketing Agency in Delhi",
    category: "Email Marketing",
    date: "Mar 6, 2026",
    author: "MarkTale Team",
    readTime: "7 min read",
    status: "Published",
  },
  {
    id: 2,
    slug: "a-guide-to-performance-marketing-strategies-in-delhi",
    title: "A Guide to Performance Marketing Strategies in Delhi",
    category: "Performance Marketing",
    date: "Mar 6, 2026",
    author: "MarkTale Team",
    readTime: "9 min read",
    status: "Published",
  },
  {
    id: 3,
    slug: "the-death-of-traditional-seo-intent-is-king",
    title: "The Death of Traditional SEO: Intent is King",
    category: "SEO Strategy",
    date: "Oct 12, 2024",
    author: "Kautilya Kalyan",
    readTime: "5 min read",
    status: "Published",
  },
  {
    id: 4,
    slug: "how-to-scale-react-apps-for-high-traffic",
    title: "How to Scale React Apps for High Traffic",
    category: "Tech",
    date: "Sep 28, 2024",
    author: "Dev Team",
    readTime: "7 min read",
    status: "Draft",
  },
  {
    id: 5,
    slug: "startup-growth-hacking-the-first-90-days",
    title: "Startup Growth Hacking: The First 90 Days",
    category: "Startups",
    date: "Sep 15, 2024",
    author: "Strategy Team",
    readTime: "6 min read",
    status: "Published",
  },
  {
    id: 6,
    slug: "ai-in-marketing-tool-or-threat",
    title: "AI in Marketing: Tool or Threat?",
    category: "AI",
    date: "Aug 30, 2024",
    author: "Kautilya Kalyan",
    readTime: "8 min read",
    status: "Published",
  },
  {
    id: 7,
    slug: "designing-for-conversion",
    title: "Designing for Conversion",
    category: "Design",
    date: "Aug 10, 2024",
    author: "Design Team",
    readTime: "5 min read",
    status: "Draft",
  },
  {
    id: 8,
    slug: "the-future-of-ridesharing-apps",
    title: "The Future of Ridesharing Apps",
    category: "Case Study",
    date: "July 22, 2024",
    author: "Product Team",
    readTime: "9 min read",
    status: "Published",
  },
];

export const CATEGORIES = [
  "Email Marketing",
  "Performance Marketing",
  "SEO Strategy",
  "Tech",
  "Startups",
  "AI",
  "Design",
  "Case Study",
  "Branding",
];

export const INITIAL_SERVICES = [
  { id: 1, name: "Android and iOS Development", active: true },
  { id: 2, name: "Web Development Services", active: true },
  { id: 3, name: "Market Research", active: true },
  { id: 4, name: "Marketing Plan Development", active: true },
  { id: 5, name: "Performance Marketing", active: true },
  { id: 6, name: "SEO & Analytics", active: true },
];

export const INITIAL_TEAM = [
  {
    id: 1,
    name: "Kautilya Kalyan",
    role: "Founder & CEO",
    email: "kautilya@marktaleworld.com",
    avatar: "KK",
  },
  {
    id: 2,
    name: "MarkTale Team",
    role: "Content Team",
    email: "content@marktaleworld.com",
    avatar: "MT",
  },
  {
    id: 3,
    name: "Dev Team",
    role: "Development",
    email: "dev@marktaleworld.com",
    avatar: "DT",
  },
  {
    id: 4,
    name: "Design Team",
    role: "UI/UX Design",
    email: "design@marktaleworld.com",
    avatar: "DS",
  },
  {
    id: 5,
    name: "Strategy Team",
    role: "Growth Strategy",
    email: "strategy@marktaleworld.com",
    avatar: "ST",
  },
];

export const NAV_ITEMS = [
  { id: "overview", icon: "Dashboard", label: "Overview" },
  { id: "blogs", icon: "Blog", label: "Blogs" },
  { id: "services", icon: "Services", label: "Services" },
  { id: "team", icon: "Team", label: "Team" },
  { id: "settings", icon: "Settings", label: "Settings" },
];
